#pragma once
#define GOOD_MOVE 0
#define GOOD_MOVE_WITH_CHECK 1
#define NO_PIECE_SELECTED 2
#define ALREDY_PIECE_IN_DST 3
#define MOVEMENT_MAKE_CHECK 4
#define INVALID_COORDINATE 5
#define INVALID_MOVEMENT 6
#define COORDINATE_EQUALS_CURRENT 7
#define /*Bonus*/ CHECKMATE 8
